repos:

  # https://github.com/pre-commit/pre-commit-hooks#pre-commit-hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.9 # Ruff version
    hooks:
      # Run the linter
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --extend-select, I]
      # Run the formatter
      - id: ruff-format
