version: '3.7'
services:
  test_database:
    image: "postgres" # use latest official postgres version
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5433:5432
