import json
import logging

from asyncpg import Record
from asyncpg.exceptions import UndefinedTableError
from csv_detective.utils import sanitize_for_json

from udata_hydra import context
from udata_hydra.utils import ParseException

log = logging.getLogger("udata-hydra")


async def get_previous_inspection(resource_id: str) -> dict | None:
    db = await context.pool("csv")
    q = (
        "SELECT parsing_table, csv_detective FROM tables_index "
        f"WHERE resource_id='{resource_id}' ORDER BY created_at DESC LIMIT 1"
    )
    res = await db.fetch(q)
    if not res:
        return None
    inspection = json.loads(res[0]["csv_detective"])
    # the csv_detective column is JSONB, so keys are reordered compared to the actual table
    # so we get the right order from the table
    try:
        rows: list[Record] = await db.fetch(f'SELECT * FROM "{res[0]["parsing_table"]}" LIMIT 1')
    except UndefinedTableError:
        log.error(f"Could not find table {res[0]['parsing_table']} for resource {resource_id}")
        return None
    if len(rows) == 0:
        return None
    # the __id column is generated by hydra, not natively in the data
    table_columns = [col for col in rows[0].keys() if col != "__id"]
    inspection["columns"] = {col: inspection["columns"][col] for col in table_columns}
    return inspection


async def insert_tables_index_entry(
    table_name: str, inspection: dict, check: Record | dict, dataset_id: str | None
) -> None:
    """Insert metadata for a parsed table into `DATABASE_URL_CSV.tables_index`."""
    db = await context.pool("csv")
    q = "INSERT INTO tables_index(parsing_table, csv_detective, resource_id, dataset_id, url) VALUES($1, $2, $3, $4, $5)"
    try:
        await db.execute(
            q,
            table_name,
            json.dumps(sanitize_for_json(inspection), default=str),
            check.get("resource_id"),
            dataset_id,
            check.get("url"),
        )
    except Exception as e:
        raise ParseException(
            message=str(e),
            step="tables_index_insertion",
            resource_id=check.get("resource_id"),
            url=check.get("url"),
            check_id=check["id"],
        ) from e
